export const DEFAULT_CONTEST_PAYOUTS = [
    {
        percentLikelihood: 1,
        odds: 5000,
        inverseOdds: -100000,
        oddsInverse: -95000,
        betPayout: 50.0,
        inverseBetPayout: 51.0,
        inversePayout: 0.51,
    },
    {
        percentLikelihood: 2,
        odds: 2500,
        inverseOdds: -7500,
        oddsInverse: -5000,
        betPayout: 25.0,
        inverseBetPayout: 25.6,
        inversePayout: 3.41,
    },
    {
        percentLikelihood: 3,
        odds: 2000,
        inverseOdds: -5000,
        oddsInverse: -3000,
        betPayout: 20.0,
        inverseBetPayout: 20.5,
        inversePayout: 4.1,
    },
    {
        percentLikelihood: 4,
        odds: 1500,
        inverseOdds: -4000,
        oddsInverse: -2500,
        betPayout: 15.0,
        inverseBetPayout: 15.4,
        inversePayout: 3.85,
    },
    {
        percentLikelihood: 5,
        odds: 1350,
        inverseOdds: -2500,
        oddsInverse: -1150,
        betPayout: 13.5,
        inverseBetPayout: 14.0,
        inversePayout: 5.6,
    },
    {
        percentLikelihood: 6,
        odds: 1200,
        inverseOdds: -2000,
        oddsInverse: -800,
        betPayout: 12.0,
        inverseBetPayout: 12.4,
        inversePayout: 6.2,
    },
    {
        percentLikelihood: 7,
        odds: 1100,
        inverseOdds: -1800,
        oddsInverse: -700,
        betPayout: 11.0,
        inverseBetPayout: 11.4,
        inversePayout: 6.33,
    },
    {
        percentLikelihood: 8,
        odds: 1000,
        inverseOdds: -1500,
        oddsInverse: -500,
        betPayout: 10.0,
        inverseBetPayout: 10.3,
        inversePayout: 6.87,
    },
    {
        percentLikelihood: 9,
        odds: 900,
        inverseOdds: -1250,
        oddsInverse: -350,
        betPayout: 9.0,
        inverseBetPayout: 9.3,
        inversePayout: 7.44,
    },
    {
        percentLikelihood: 10,
        odds: 800,
        inverseOdds: -1100,
        oddsInverse: -300,
        betPayout: 8.0,
        inverseBetPayout: 8.25,
        inversePayout: 7.5,
    },
    {
        percentLikelihood: 11,
        odds: 700,
        inverseOdds: -1000,
        oddsInverse: -300,
        betPayout: 7.0,
        inverseBetPayout: 7.25,
        inversePayout: 7.25,
    },
    {
        percentLikelihood: 12,
        odds: 650,
        inverseOdds: -850,
        oddsInverse: -200,
        betPayout: 6.5,
        inverseBetPayout: 6.7,
        inversePayout: 7.88,
    },
    {
        percentLikelihood: 13,
        odds: 600,
        inverseOdds: -725,
        oddsInverse: -125,
        betPayout: 6.0,
        inverseBetPayout: 6.2,
        inversePayout: 8.55,
    },
    {
        percentLikelihood: 14,
        odds: 550,
        inverseOdds: -660,
        oddsInverse: -110,
        betPayout: 5.5,
        inverseBetPayout: 5.65,
        inversePayout: 8.56,
    },
    {
        percentLikelihood: 15,
        odds: 500,
        inverseOdds: -600,
        oddsInverse: -100,
        betPayout: 5.0,
        inverseBetPayout: 5.15,
        inversePayout: 8.58,
    },
    {
        percentLikelihood: 16,
        odds: 450,
        inverseOdds: -550,
        oddsInverse: -100,
        betPayout: 4.5,
        inverseBetPayout: 4.65,
        inversePayout: 8.45,
    },
    {
        percentLikelihood: 17,
        odds: 425,
        inverseOdds: -525,
        oddsInverse: -100,
        betPayout: 4.25,
        inverseBetPayout: 4.45,
        inversePayout: 8.48,
    },
    {
        percentLikelihood: 18,
        odds: 400,
        inverseOdds: -475,
        oddsInverse: -75,
        betPayout: 4.0,
        inverseBetPayout: 4.1,
        inversePayout: 8.63,
    },
    {
        percentLikelihood: 19,
        odds: 375,
        inverseOdds: -450,
        oddsInverse: -75,
        betPayout: 3.75,
        inverseBetPayout: 3.9,
        inversePayout: 8.67,
    },
    {
        percentLikelihood: 20,
        odds: 360,
        inverseOdds: -425,
        oddsInverse: -65,
        betPayout: 3.6,
        inverseBetPayout: 3.7,
        inversePayout: 8.71,
    },
    {
        percentLikelihood: 21,
        odds: 340,
        inverseOdds: -400,
        oddsInverse: -60,
        betPayout: 3.4,
        inverseBetPayout: 3.5,
        inversePayout: 8.75,
    },
    {
        percentLikelihood: 22,
        odds: 320,
        inverseOdds: -375,
        oddsInverse: -55,
        betPayout: 3.2,
        inverseBetPayout: 3.3,
        inversePayout: 8.8,
    },
    {
        percentLikelihood: 23,
        odds: 300,
        inverseOdds: -350,
        oddsInverse: -50,
        betPayout: 3.0,
        inverseBetPayout: 3.1,
        inversePayout: 8.86,
    },
    {
        percentLikelihood: 24,
        odds: 285,
        inverseOdds: -330,
        oddsInverse: -45,
        betPayout: 2.85,
        inverseBetPayout: 2.95,
        inversePayout: 8.94,
    },
    {
        percentLikelihood: 25,
        odds: 270,
        inverseOdds: -320,
        oddsInverse: -50,
        betPayout: 2.7,
        inverseBetPayout: 2.8,
        inversePayout: 8.75,
    },
    {
        percentLikelihood: 26,
        odds: 255,
        inverseOdds: -300,
        oddsInverse: -45,
        betPayout: 2.55,
        inverseBetPayout: 2.7,
        inversePayout: 9.0,
    },
    {
        percentLikelihood: 27,
        odds: 245,
        inverseOdds: -280,
        oddsInverse: -35,
        betPayout: 2.45,
        inverseBetPayout: 2.55,
        inversePayout: 9.11,
    },
    {
        percentLikelihood: 28,
        odds: 235,
        inverseOdds: -265,
        oddsInverse: -30,
        betPayout: 2.35,
        inverseBetPayout: 2.4,
        inversePayout: 9.06,
    },
    {
        percentLikelihood: 29,
        odds: 225,
        inverseOdds: -255,
        oddsInverse: -30,
        betPayout: 2.25,
        inverseBetPayout: 2.3,
        inversePayout: 9.02,
    },
    {
        percentLikelihood: 30,
        odds: 215,
        inverseOdds: -240,
        oddsInverse: -25,
        betPayout: 2.15,
        inverseBetPayout: 2.25,
        inversePayout: 9.38,
    },
    {
        percentLikelihood: 31,
        odds: 200,
        inverseOdds: -230,
        oddsInverse: -30,
        betPayout: 2.0,
        inverseBetPayout: 2.1,
        inversePayout: 9.13,
    },
    {
        percentLikelihood: 32,
        odds: 190,
        inverseOdds: -220,
        oddsInverse: -30,
        betPayout: 1.9,
        inverseBetPayout: 2.0,
        inversePayout: 9.09,
    },
    {
        percentLikelihood: 33,
        odds: 185,
        inverseOdds: -210,
        oddsInverse: -25,
        betPayout: 1.85,
        inverseBetPayout: 1.93,
        inversePayout: 9.17,
    },
    {
        percentLikelihood: 34,
        odds: 180,
        inverseOdds: -200,
        oddsInverse: -20,
        betPayout: 1.8,
        inverseBetPayout: 1.88,
        inversePayout: 9.38,
    },
    {
        percentLikelihood: 35,
        odds: 170,
        inverseOdds: -195,
        oddsInverse: -25,
        betPayout: 1.7,
        inverseBetPayout: 1.78,
        inversePayout: 9.1,
    },
    {
        percentLikelihood: 36,
        odds: 165,
        inverseOdds: -185,
        oddsInverse: -20,
        betPayout: 1.65,
        inverseBetPayout: 1.7,
        inversePayout: 9.19,
    },
    {
        percentLikelihood: 37,
        odds: 160,
        inverseOdds: -175,
        oddsInverse: -15,
        betPayout: 1.6,
        inverseBetPayout: 1.65,
        inversePayout: 9.43,
    },
    {
        percentLikelihood: 38,
        odds: 155,
        inverseOdds: -170,
        oddsInverse: -15,
        betPayout: 1.55,
        inverseBetPayout: 1.6,
        inversePayout: 9.41,
    },
    {
        percentLikelihood: 39,
        odds: 150,
        inverseOdds: -160,
        oddsInverse: -10,
        betPayout: 1.5,
        inverseBetPayout: 1.55,
        inversePayout: 9.69,
    },
    {
        percentLikelihood: 40,
        odds: 145,
        inverseOdds: -155,
        oddsInverse: -10,
        betPayout: 1.45,
        inverseBetPayout: 1.5,
        inversePayout: 9.68,
    },
    {
        percentLikelihood: 41,
        odds: 140,
        inverseOdds: -150,
        oddsInverse: -10,
        betPayout: 1.4,
        inverseBetPayout: 1.45,
        inversePayout: 9.67,
    },
    {
        percentLikelihood: 42,
        odds: 135,
        inverseOdds: -145,
        oddsInverse: -10,
        betPayout: 1.35,
        inverseBetPayout: 1.4,
        inversePayout: 9.66,
    },
    {
        percentLikelihood: 43,
        odds: 130,
        inverseOdds: -140,
        oddsInverse: -10,
        betPayout: 1.3,
        inverseBetPayout: 1.35,
        inversePayout: 9.64,
    },
    {
        percentLikelihood: 44,
        odds: 125,
        inverseOdds: -135,
        oddsInverse: -10,
        betPayout: 1.25,
        inverseBetPayout: 1.3,
        inversePayout: 9.63,
    },
    {
        percentLikelihood: 45,
        odds: 120,
        inverseOdds: -130,
        oddsInverse: -10,
        betPayout: 1.2,
        inverseBetPayout: 1.25,
        inversePayout: 9.62,
    },
    {
        percentLikelihood: 46,
        odds: 115,
        inverseOdds: -125,
        oddsInverse: -10,
        betPayout: 1.15,
        inverseBetPayout: 1.2,
        inversePayout: 9.6,
    },
    {
        percentLikelihood: 47,
        odds: 110,
        inverseOdds: -120,
        oddsInverse: -10,
        betPayout: 1.1,
        inverseBetPayout: 1.15,
        inversePayout: 9.58,
    },
    {
        percentLikelihood: 48,
        odds: 105,
        inverseOdds: -115,
        oddsInverse: -10,
        betPayout: 1.05,
        inverseBetPayout: 1.1,
        inversePayout: 9.57,
    },
    {
        percentLikelihood: 49,
        odds: 100,
        inverseOdds: -110,
        oddsInverse: -10,
        betPayout: 1.0,
        inverseBetPayout: 1.05,
        inversePayout: 9.55,
    },
    {
        percentLikelihood: 50,
        odds: -105,
        inverseOdds: -105,
        oddsInverse: 0,
        betPayout: 0.95,
        inverseBetPayout: 1.0,
        inversePayout: 9.52,
    },
    {
        percentLikelihood: 51,
        odds: -110,
        inverseOdds: 100,
        oddsInverse: 10,
        betPayout: 0.91,
        inverseBetPayout: 0.95,
        inversePayout: 9.5,
    },
    {
        percentLikelihood: 52,
        odds: -115,
        inverseOdds: 105,
        oddsInverse: 10,
        betPayout: 0.87,
        inverseBetPayout: 0.9,
        inversePayout: 9.45,
    },
    {
        percentLikelihood: 53,
        odds: -120,
        inverseOdds: 110,
        oddsInverse: 10,
        betPayout: 0.83,
        inverseBetPayout: 0.88,
        inversePayout: 9.63,
    },
    {
        percentLikelihood: 54,
        odds: -125,
        inverseOdds: 115,
        oddsInverse: 10,
        betPayout: 0.8,
        inverseBetPayout: 0.84,
        inversePayout: 9.6,
    },
    {
        percentLikelihood: 55,
        odds: -130,
        inverseOdds: 120,
        oddsInverse: 10,
        betPayout: 0.77,
        inverseBetPayout: 0.8,
        inversePayout: 9.6,
    },
    {
        percentLikelihood: 56,
        odds: -135,
        inverseOdds: 125,
        oddsInverse: 10,
        betPayout: 0.74,
        inverseBetPayout: 0.78,
        inversePayout: 9.69,
    },
    {
        percentLikelihood: 57,
        odds: -140,
        inverseOdds: 130,
        oddsInverse: 10,
        betPayout: 0.71,
        inverseBetPayout: 0.75,
        inversePayout: 9.75,
    },
    {
        percentLikelihood: 58,
        odds: -145,
        inverseOdds: 135,
        oddsInverse: 10,
        betPayout: 0.69,
        inverseBetPayout: 0.72,
        inversePayout: 9.72,
    },
    {
        percentLikelihood: 59,
        odds: -150,
        inverseOdds: 140,
        oddsInverse: 10,
        betPayout: 0.67,
        inverseBetPayout: 0.7,
        inversePayout: 9.8,
    },
    {
        percentLikelihood: 60,
        odds: -155,
        inverseOdds: 145,
        oddsInverse: 10,
        betPayout: 0.65,
        inverseBetPayout: 0.67,
        inversePayout: 9.72,
    },
    {
        percentLikelihood: 61,
        odds: -160,
        inverseOdds: 150,
        oddsInverse: 10,
        betPayout: 0.63,
        inverseBetPayout: 0.65,
        inversePayout: 9.75,
    },
    {
        percentLikelihood: 62,
        odds: -170,
        inverseOdds: 155,
        oddsInverse: 15,
        betPayout: 0.59,
        inverseBetPayout: 0.62,
        inversePayout: 9.61,
    },
    {
        percentLikelihood: 63,
        odds: -175,
        inverseOdds: 160,
        oddsInverse: 15,
        betPayout: 0.57,
        inverseBetPayout: 0.6,
        inversePayout: 9.6,
    },
    {
        percentLikelihood: 64,
        odds: -185,
        inverseOdds: 165,
        oddsInverse: 20,
        betPayout: 0.54,
        inverseBetPayout: 0.58,
        inversePayout: 9.57,
    },
    {
        percentLikelihood: 65,
        odds: -195,
        inverseOdds: 170,
        oddsInverse: 25,
        betPayout: 0.51,
        inverseBetPayout: 0.56,
        inversePayout: 9.52,
    },
    {
        percentLikelihood: 66,
        odds: -200,
        inverseOdds: 180,
        oddsInverse: 20,
        betPayout: 0.5,
        inverseBetPayout: 0.54,
        inversePayout: 9.72,
    },
    {
        percentLikelihood: 67,
        odds: -210,
        inverseOdds: 185,
        oddsInverse: 25,
        betPayout: 0.48,
        inverseBetPayout: 0.52,
        inversePayout: 9.62,
    },
    {
        percentLikelihood: 68,
        odds: -220,
        inverseOdds: 190,
        oddsInverse: 30,
        betPayout: 0.45,
        inverseBetPayout: 0.5,
        inversePayout: 9.5,
    },
    {
        percentLikelihood: 69,
        odds: -230,
        inverseOdds: 200,
        oddsInverse: 30,
        betPayout: 0.43,
        inverseBetPayout: 0.48,
        inversePayout: 9.6,
    },
    {
        percentLikelihood: 70,
        odds: -240,
        inverseOdds: 215,
        oddsInverse: 25,
        betPayout: 0.42,
        inverseBetPayout: 0.45,
        inversePayout: 9.68,
    },
    {
        percentLikelihood: 71,
        odds: -255,
        inverseOdds: 225,
        oddsInverse: 30,
        betPayout: 0.39,
        inverseBetPayout: 0.43,
        inversePayout: 9.56,
    },
    {
        percentLikelihood: 72,
        odds: -265,
        inverseOdds: 235,
        oddsInverse: 30,
        betPayout: 0.38,
        inverseBetPayout: 0.41,
        inversePayout: 9.64,
    },
    {
        percentLikelihood: 73,
        odds: -280,
        inverseOdds: 245,
        oddsInverse: 35,
        betPayout: 0.36,
        inverseBetPayout: 0.39,
        inversePayout: 9.56,
    },
    {
        percentLikelihood: 74,
        odds: -300,
        inverseOdds: 255,
        oddsInverse: 45,
        betPayout: 0.33,
        inverseBetPayout: 0.38,
        inversePayout: 9.56,
    },
    {
        percentLikelihood: 75,
        odds: -320,
        inverseOdds: 270,
        oddsInverse: 50,
        betPayout: 0.31,
        inverseBetPayout: 0.35,
        inversePayout: 9.45,
    },
    {
        percentLikelihood: 76,
        odds: -330,
        inverseOdds: 285,
        oddsInverse: 45,
        betPayout: 0.3,
        inverseBetPayout: 0.34,
        inversePayout: 9.69,
    },
    {
        percentLikelihood: 77,
        odds: -350,
        inverseOdds: 300,
        oddsInverse: 50,
        betPayout: 0.29,
        inverseBetPayout: 0.32,
        inversePayout: 9.6,
    },
    {
        percentLikelihood: 78,
        odds: -375,
        inverseOdds: 320,
        oddsInverse: 55,
        betPayout: 0.27,
        inverseBetPayout: 0.3,
        inversePayout: 9.6,
    },
    {
        percentLikelihood: 79,
        odds: -400,
        inverseOdds: 340,
        oddsInverse: 60,
        betPayout: 0.25,
        inverseBetPayout: 0.28,
        inversePayout: 9.35,
    },
    {
        percentLikelihood: 80,
        odds: -425,
        inverseOdds: 360,
        oddsInverse: 65,
        betPayout: 0.24,
        inverseBetPayout: 0.26,
        inversePayout: 9.36,
    },
    {
        percentLikelihood: 81,
        odds: -450,
        inverseOdds: 375,
        oddsInverse: 75,
        betPayout: 0.22,
        inverseBetPayout: 0.25,
        inversePayout: 9.38,
    },
    {
        percentLikelihood: 82,
        odds: -475,
        inverseOdds: 400,
        oddsInverse: 75,
        betPayout: 0.21,
        inverseBetPayout: 0.24,
        inversePayout: 9.4,
    },
    {
        percentLikelihood: 83,
        odds: -525,
        inverseOdds: 425,
        oddsInverse: 100,
        betPayout: 0.19,
        inverseBetPayout: 0.23,
        inversePayout: 9.56,
    },
    {
        percentLikelihood: 84,
        odds: -550,
        inverseOdds: 450,
        oddsInverse: 100,
        betPayout: 0.18,
        inverseBetPayout: 0.21,
        inversePayout: 9.45,
    },
    {
        percentLikelihood: 85,
        odds: -600,
        inverseOdds: 500,
        oddsInverse: 100,
        betPayout: 0.17,
        inverseBetPayout: 0.19,
        inversePayout: 9.5,
    },
    {
        percentLikelihood: 86,
        odds: -660,
        inverseOdds: 550,
        oddsInverse: 110,
        betPayout: 0.15,
        inverseBetPayout: 0.18,
        inversePayout: 9.63,
    },
    {
        percentLikelihood: 87,
        odds: -725,
        inverseOdds: 600,
        oddsInverse: 125,
        betPayout: 0.14,
        inverseBetPayout: 0.16,
        inversePayout: 9.6,
    },
    {
        percentLikelihood: 88,
        odds: -850,
        inverseOdds: 650,
        oddsInverse: 200,
        betPayout: 0.12,
        inverseBetPayout: 0.15,
        inversePayout: 9.75,
    },
    {
        percentLikelihood: 89,
        odds: -1000,
        inverseOdds: 700,
        oddsInverse: 300,
        betPayout: 0.1,
        inverseBetPayout: 0.14,
        inversePayout: 9.8,
    },
    {
        percentLikelihood: 90,
        odds: -1100,
        inverseOdds: 800,
        oddsInverse: 300,
        betPayout: 0.09,
        inverseBetPayout: 0.12,
        inversePayout: 9.6,
    },
    {
        percentLikelihood: 91,
        odds: -1250,
        inverseOdds: 900,
        oddsInverse: 350,
        betPayout: 0.08,
        inverseBetPayout: 0.1,
        inversePayout: 9.0,
    },
    {
        percentLikelihood: 92,
        odds: -1500,
        inverseOdds: 1000,
        oddsInverse: 500,
        betPayout: 0.07,
        inverseBetPayout: 0.09,
        inversePayout: 9.0,
    },
    {
        percentLikelihood: 93,
        odds: -1800,
        inverseOdds: 1100,
        oddsInverse: 700,
        betPayout: 0.06,
        inverseBetPayout: 0.08,
        inversePayout: 8.8,
    },
    {
        percentLikelihood: 94,
        odds: -2000,
        inverseOdds: 1200,
        oddsInverse: 800,
        betPayout: 0.05,
        inverseBetPayout: 0.08,
        inversePayout: 9.0,
    },
    {
        percentLikelihood: 95,
        odds: -2500,
        inverseOdds: 1350,
        oddsInverse: 1150,
        betPayout: 0.04,
        inverseBetPayout: 0.07,
        inversePayout: 8.78,
    },
    {
        percentLikelihood: 96,
        odds: -4000,
        inverseOdds: 1500,
        oddsInverse: 2500,
        betPayout: 0.03,
        inverseBetPayout: 0.06,
        inversePayout: 9.0,
    },
    {
        percentLikelihood: 97,
        odds: -5000,
        inverseOdds: 2000,
        oddsInverse: 3000,
        betPayout: 0.02,
        inverseBetPayout: 0.05,
        inversePayout: 9.0,
    },
    {
        percentLikelihood: 98,
        odds: -7500,
        inverseOdds: 2500,
        oddsInverse: 5000,
        betPayout: 0.01,
        inverseBetPayout: 0.04,
        inversePayout: 8.75,
    },
    {
        percentLikelihood: 99,
        odds: -100000,
        inverseOdds: 5000,
        oddsInverse: 95000,
        betPayout: 0.0,
        inverseBetPayout: 0.01,
        inversePayout: 5.0,
    },
];
